version: "3.1"

services:
  postgres_f:
    container_name: postgres_f
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.1

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres_f
    ports:
      - 5050:8080
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.5

  ws-firmaec:
    image: spring/firmaec_ws
    container_name: ws-firmaec
    restart: always
    depends_on:
      - mintel-firmaec
      - postgres_f
    ports:
      - 8090:8090
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.database=POSTGRESQL
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.defer-datasource-initialization=true
      - spring.sql.init.mode=always
      - spring.datasource.url=${DB_JDBC_POSTGRES}
      - spring.datasource.username=${DB_USER_POSTGRES}
      - spring.datasource.password=${DB_PASSWORD_POSTGRES}
      - url.externa=http://172.29.0.2:8080/
      - app.apikey=${APP_APIKEY}
      - app.apikeyrest=${APP_APIKEYREST}
      - app.urlapi=http://172.29.0.3:8090/iess/firmaec
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.3

  mintel-firmaec:
    image: jboss/wildfly-admin
    container_name: mintel-firmaec
    restart: always
    depends_on:
      - postgres_f
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - DB_URL_POSTGRES=${DB_JDBC_POSTGRES}
      - DB_USER_POSTGRES=${DB_USER_POSTGRES}
      - DB_PASSWORD_POSTGRES=${DB_PASSWORD_POSTGRES}
    volumes:
      - ./Wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.2

volumes:
  db:
    driver: local

networks:
  network_firmaec:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          ip_range: 172.29.0.0/24
          gateway: 172.29.0.254

